### ISSUE TITLE
[Bug] iPad Version of YTMusicUltimate isn’t sized correctly

### ISSUE THREAD

**Issue by arichorn** [ginsudev/YTMusicUltimate#10] opened 2022-08-13 16:03 UTC
![B066C5FA-5CCA-4989-9530-8C946B04442B](https://user-images.githubusercontent.com/78001398/184501794-153a9427-85f0-4cec-98b6-bb6987a5c1ec.jpeg)
If anyone else has this issue, then might as well use the iPhone version of YTMusicUltimate because on the iPad version you can’t even press the options 😭

**Comment by at001475** [comment] 2022-08-22 01:41
> ![B066C5FA-5CCA-4989-9530-8C946B04442B](https://user-images.githubusercontent.com/78001398/184501794-153a9427-85f0-4cec-98b6-bb6987a5c1ec.jpeg)
> 
> If anyone else has this issue, then might as well use the iPhone version of YTMusicUltimate because on the iPad version you can’t even press the options 😭

Wait you can install it? I was stuck at the installation in AltStore

**Comment by arichorn** [comment] 2022-08-22 02:07
That’s my version of the ipa,
ginsudev uses a weirder version of the YouTube Music ipa and probably takes out the iPad support.

My version lets me build it and able to run on iPads. But YTMusicUltimate on iPad is broken still due to unsized elements

also if you want this ipa then here ya go https://github.com/arichorn/YTMusicUltimate/releases/tag/v5.19

**Comment by arichorn** [comment] 2022-08-22 03:53
https://github.com/arichorn/YTMusicUltimate/releases/download/v5.20-1.1.6-(3)/YTMusicUltimate_5.20_1.1.6.ipa
also here’s this if you want to use this with the latest version of YTMusic as of right now.
Don’t use this on any of the iPad devices just because the scaling on there will hide all of the YTMusicUltimate Features.

**Comment by ginsudev** [comment] 2022-08-22 05:10
> https://github.com/arichorn/YTMusicUltimate/releases/download/v5.20-1.1.6-(3)/YTMusicUltimate_5.20_1.1.6.ipa
> 
> also here’s this if you want to use this with the latest version of YTMusic as of right now.
> 
> Don’t use this on any of the iPad devices just because the scaling on there will hide all of the YTMusicUltimate Features.

For now you can turn your iPad to portrait mode and it'll work. I'll fix the issue in the next version

**Comment by ginsudev** [comment] 2022-08-22 10:11
> That’s my version of the ipa, ginsudev uses a weirder version of the YouTube Music ipa and probably takes out the iPad support.
> 
> My version lets me build it and able to run on iPads. But YTMusicUltimate on iPad is broken still due to unsized elements
> 
> also if you want this ipa then here ya go https://github.com/arichorn/YTMusicUltimate/releases/tag/v5.19

I've actually been using iPA's from iOS Gods all along btw, never removed iPad support. But anyway, the issue is fixed now.

**Closed by ginsudev** 2022-08-22 10:11 UTC

**Comment by arichorn** [comment] 2022-08-22 21:02
Oh thanks! I didn’t know you used the same site I use sorry! 🥺
